Finish Login Screen
fernandolfla/pizzaria_front pull request #3
Opened 2023-03-18 00:50 UTC by FidelisSantos

2023-03-19 12:32 UTC, fernandolfla approved these changes
Aprovado

2023-03-20 14:12 UTC, FagnerFun requested changes
**Tela Inicial**

-Wpp - Links e botões do wpp sem redirecionamento
- Botão login - colado com cabeçalho, fora do espçamento do prototipo 
- Texto "onde estamos" - em negrito, fora não seguindo padrão do prototipo
- botão de telefone na seção onde estamos clivavel sem redirecionamento
- Fotos do instagram não disponiveis, conforme prototipo
- Logo no rodapé em texto
- logo no cabeçalho não apresentada
- Layout quebra na resolução 1024x768

Tela Login

- Espaçamento entre as duas caixas de conteudo diferente do prototipo
- Links de redes sociais direcionando somente para facebook
- snackbar de erro fora do alinhamento desenhado no prototipo (muito a direita)
- campo senha não esconde a senha 🤡
- Ordenação dos campos ao ir dando tab, não seleciona campo lembrar senha

2023-03-25 20:41 UTC, FidelisSantos commented
Sobre a tela principal, como conversamos que iria haver alterações primeiro aguardarei as alterações para já trazer a fix com as melhorias, seria trabalho dobrado fazer sabendo que teria que ser refeito... desse modo podemos já mostrar o fluxo de login, 

OBS: Lembrando que a principal já está em develop por isso não haverá alteração no momento, só foi remodelada questão de pastas

2023-03-25 20:43 UTC, fernandolfla approved these changes

2023-03-28 23:06 UTC, merged